load("//tools:module.bzl", "pi_interface")

pi_interface(
    name = "virtual_resolve_request",
    deps = [
        "//interfaces/support/abort_signal",
        "//interfaces/types/assistant_message",
        "//interfaces/types/json",
        "//interfaces/types/message",
        "//interfaces/types/model",
        "//interfaces/types/thinking_level",
    ],
)
