load("//tools:module.bzl", "pi_support")

pi_support(
    name = "oauth_token_mapper",
    deps = [
        "//interfaces/platform/i_base64_codec",
        "//interfaces/platform/i_clock",
        "//interfaces/platform/i_http_client",
        "//interfaces/types/credential",
        "//interfaces/types/json",
        "//interfaces/types/oauth_refresh_spec",
        "//interfaces/types/result",
    ],
    test_deps = [
        "//interfaces/support/builtin_oauth_specs",
        "//src/base/base64_codec",
        "//src/testing/fixed_clock",
    ],
)
