load("//tools:module.bzl", "pi_support")

pi_support(
    name = "live_editor",
    deps = [
        "//interfaces/support/transaction",
        "//interfaces/types/json",
        "//interfaces/types/result",
    ],
    test_deps = [
        "//interfaces/support/durable_session",
        "//src/durable/memory_storage",
    ],
)
