load("//tools:module.bzl", "pi_support")

pi_support(
    name = "remote_service_endpoint",
    deps = [
        "//interfaces/chord/i_service_endpoint",
        "//interfaces/chord/i_service_provider",
        "//interfaces/support/service_wire",
    ],
    test_deps = [
        "//interfaces/support/remote_service_provider",
        "//interfaces/support/replicated_state",
    ],
)
