load("//tools:module.bzl", "pi_interface")

pi_interface(
    name = "session_router_options",
    deps = [
        "//interfaces/platform/i_executor",
        "//interfaces/platform/i_id_generator",
        "//interfaces/server/i_server_host",
        "//interfaces/types/error",
        "//interfaces/types/service_context",
        "//interfaces/types/session_attachment",
    ],
)
