load("//tools:module.bzl", "pi_module")

pi_module(
    name = "directory_session_catalog",
    deps = [
        "//interfaces/platform/i_clock",
        "//interfaces/platform/i_file_system",
        "//interfaces/platform/i_id_generator",
        "//interfaces/server/i_session_catalog",
        "//interfaces/types/json",
    ],
    test_deps = [
        "//src/testing/fake_file_system",
        "//src/testing/fixed_clock",
        "//src/testing/sequential_id_generator",
    ],
)
