load("//tools:module.bzl", "pi_interface")

pi_interface(
    name = "i_server_service_host",
    deps = [
        "//interfaces/server/i_server_presentation",
        "//interfaces/server/i_service_attachment",
        "//interfaces/types/result",
        "//interfaces/types/service_context",
    ],
)
