import { spawn } from "node:child_process";
import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Client } from "@earendil-works/pi-client";
import { createUnixTransportFactory } from "@earendil-works/pi-client/unix";
const PI = process.env.PI_BINARY ?? "bazel-bin/app/pi/pi";
const SERVER_ID = "01234567-89ab-4def-8123-456789abcdef";
const root = mkdtempSync(join(tmpdir(), "import-"));
const dir = join(root, "agent", "server-sessions", "imported");
mkdirSync(dir, { recursive: true });
copyFileSync(process.argv[2], join(dir, "session.sqlite"));
writeFileSync(join(dir, "meta.json"), JSON.stringify({ createdAt: 1700000000000, cwd: root }));
const child = spawn(PI, ["serve", "--faux", "--server-dir", join(root, "srv"), "--server-id", SERVER_ID, "--agent-dir", join(root, "agent")], { cwd: root, env: { ...process.env, PI_FAUX_REPLIES: JSON.stringify(["second answer"]), HOME: root }, stdio: ["ignore", "inherit", "inherit"] });
const sock = join(root, "srv", `${SERVER_ID}.sock`);
for (let i = 0; i < 200 && !existsSync(sock); i++) await new Promise((r) => setTimeout(r, 25));
const call = (serviceId: string, member: string, a: unknown[]) => ({ serviceId, member, args: a }) as any;
let code = 0;
try {
	const client = new Client({ serverId: SERVER_ID, transportFactory: createUnixTransportFactory({ path: sock }) });
	await client.connect();
	const dirSub: any = await client.subscribeService({ serverId: SERVER_ID }, "pi.session-directory", "singleton", () => {});
	console.log("directory", JSON.stringify(dirSub.snapshot).slice(0, 300));
	await client.request({ serverId: SERVER_ID }, call("pi.session-management", "attach", ["imported"]));
	for (let i = 0; i < 200 && !client.attachment; i++) await new Promise((r) => setTimeout(r, 25));
	const target = client.attachment!;
	const sub: any = await client.subscribeService(target, "pi.transcript", "singleton", () => {});
	const snap = JSON.stringify(sub.snapshot);
	console.log("snapshot", snap.slice(0, 600));
	if (!snap.includes("pong from faux")) throw new Error("imported transcript lacks reply");
	const p: any = await client.request(target, call("pi.agent-controller", "prompt", [{ message: "again", images: null }]));
	console.log("prompt", JSON.stringify(p));
	const a: any = await client.request(target, call("pi.agent-controller", "waitForPrompt", [p.operationId]));
	console.log("answer", JSON.stringify(a));
	if (a.text !== "second answer") throw new Error("continuation failed");
	console.log("OK import");
	await client.dispose();
} catch (e) { console.error("FAIL", e); code = 1; }
child.kill();
process.exit(code);
