load("//tools:module.bzl", "pi_support")

pi_support(
    name = "export_theme_resolver",
    deps = [
        "//interfaces/support/theme_color_parser",
        "//interfaces/types/json",
        "//interfaces/types/result",
        "//interfaces/types/theme_token_set",
    ],
    data = ["//src/testing/ts_golden:themes"],
)
